### ISSUE TITLE
code completion does not work in event lambda

### ISSUE THREAD

**Issue by wispoffates** [DevSrSouza/KotlinBukkitAPI-Tooling#2]
```
event<BlockBreakEvent>() {
    val event = this.cast<BlockBreakEvent>()
    event.player.sendMessage("You broke a block! :: " + event.block.type)
 }
```

I end up needing to cast 'this' to the event type because code completion does not suggest anything if I do 'this.'

**Comment by wispoffates** [comment]
nvm had to do with my folder structure.  Its working now.

**Comment by DevSrSouza** [comment]
No problem @wispoffates , but for the issues with the API, plz, summit into the API repository https://github.com/DevSrSouza/KotlinBukkitAPI .

Tkx, hope the API is helping you :D
