### ISSUE TITLE
Your domain is down

### ISSUE THREAD

**Issue by SMCodesP** [DevSrSouza/KotlinBukkitAPI-Tooling#6]
Your repository domain for packages published at nexus.devsrsouza.com.br is currently unavailable. I would like to inquire if there are any plans to relocate these packages to another repository. I've been attempting to build a plugin for a more recent version of IntelliJ, but I'm facing challenges. I have limited experience with Kotlin and the Gradle builder, and I'm trying to utilize your projects to enhance my understanding. Unfortunately, I've encountered an impasse. I've already tried to build Bukkript, which is a dependency of this project and relies on the unavailable repository, but I haven't been successful.

I'm sorry for my English.

**Comment by DevSrSouza** [comment]
Foi mal brow, o projeto tá parada a um tempo e acredito que nem deve funcionar nas novas versões do IntelliJ.

**Comment by SMCodesP** [comment]
Ah sim entendo, estou tentando fazer com que funcione estava tentando prosseguir com isso, mas por enquanto tou sem progresso já na construção básica do projeto, então tinha aberto essa issue pra saber mesmo o estado, obrigado
